use argon2::{Argon2, PasswordHash, PasswordHasher, PasswordVerifier, password_hash::SaltString};
use rand_core::OsRng;
use sqlx::{sqlite::{SqliteConnectOptions, SqliteJournalMode, SqlitePoolOptions, SqliteSynchronous}, SqlitePool};
use std::{path::{Path,PathBuf}, time::{Duration,SystemTime,UNIX_EPOCH}, sync::Mutex};
use tauri::{Manager,State};
struct Auth { unlocked: bool, failures:u32, blocked_until:u64 }
struct Db { pool:SqlitePool, auth:Mutex<Auth>, path:PathBuf }
fn seconds()->u64 {SystemTime::now().duration_since(UNIX_EPOCH).unwrap_or_default().as_secs()}
fn authorized(db:&Db)->Result<(),String>{if db.auth.lock().map_err(|_|"Lock unavailable")?.unlocked {Ok(())}else{Err("Unlock the owner workspace first.".into())}}
fn report(db:&Db,e:impl std::fmt::Display)->String {let line=format!("{} {}\n",seconds(),e);use std::io::Write;let log=db.path.join("support.log");if std::fs::metadata(&log).map(|m|m.len()>2_000_000).unwrap_or(false){let _=std::fs::rename(&log,db.path.join("support.previous.log"));}if let Ok(mut f)=std::fs::OpenOptions::new().create(true).append(true).open(log){let _=f.write_all(line.as_bytes());}"The local operation could not be completed. Your previous saved data is preserved. See support.log for details.".into()}
fn hash(password:&str)->Result<String,String>{if password.len()<8 || password.len()>128{return Err("Use a password between 8 and 128 characters.".into());}Argon2::default().hash_password(password.as_bytes(),&SaltString::generate(&mut OsRng)).map(|x|x.to_string()).map_err(|_|"Could not secure the password.".into())}
async fn verify(db:&Db,password:&str)->Result<(),String>{ {let auth=db.auth.lock().map_err(|_|"Lock unavailable")?;if seconds()<auth.blocked_until{return Err("Too many attempts. Wait 30 seconds.".into());}}let stored:Option<String>=sqlx::query_scalar("SELECT hash FROM owner WHERE id=1").fetch_optional(&db.pool).await.map_err(|e|report(db,e))?;let valid=stored.as_ref().and_then(|h|PasswordHash::new(h).ok()).map(|h|Argon2::default().verify_password(password.as_bytes(),&h).is_ok()).unwrap_or(false);let mut auth=db.auth.lock().map_err(|_|"Lock unavailable")?;if valid{auth.failures=0;auth.blocked_until=0;Ok(())}else{auth.failures+=1;if auth.failures>=5{auth.blocked_until=seconds()+30;auth.failures=0;}Err("Incorrect owner password.".into())}}
#[tauri::command]
async fn has_owner(db:State<'_,Db>)->Result<bool,String>{let n:i64=sqlx::query_scalar("SELECT count(*) FROM owner").fetch_one(&db.pool).await.map_err(|e|report(&db,e))?;Ok(n==1)}
#[tauri::command]
async fn create_owner(db:State<'_,Db>,password:String)->Result<(),String>{let hashed=hash(&password)?;sqlx::query("INSERT INTO owner (id,hash) VALUES (1,?)").bind(hashed).execute(&db.pool).await.map_err(|_|"An owner already exists or the database could not be written. Unlock instead.".to_string())?;db.auth.lock().map_err(|_|"Lock unavailable")?.unlocked=true;Ok(())}
#[tauri::command]
async fn unlock(db:State<'_,Db>,password:String)->Result<(),String>{verify(&db,&password).await?;db.auth.lock().map_err(|_|"Lock unavailable")?.unlocked=true;Ok(())}
#[tauri::command]
fn lock(db:State<'_,Db>)->Result<(),String>{db.auth.lock().map_err(|_|"Lock unavailable")?.unlocked=false;Ok(())}
#[tauri::command]
async fn change_password(db:State<'_,Db>,current:String,password:String)->Result<(),String>{authorized(&db)?;verify(&db,&current).await?;let hashed=hash(&password)?;sqlx::query("UPDATE owner SET hash=? WHERE id=1").bind(hashed).execute(&db.pool).await.map_err(|e|report(&db,e))?;Ok(())}
#[tauri::command]
async fn load_state(db:State<'_,Db>)->Result<String,String>{authorized(&db)?;sqlx::query_scalar("SELECT data FROM business_state WHERE id=1").fetch_one(&db.pool).await.map_err(|e|report(&db,e))}
#[tauri::command]
async fn save_state(db:State<'_,Db>,data:String,expected:i64)->Result<(),String>{authorized(&db)?;if data.len()>100_000_000{return Err("Database snapshot exceeds this release's 100 MB limit. Contact support before continuing.".into());}let parsed:serde_json::Value=serde_json::from_str(&data).map_err(|_|"Invalid business data.")?;if parsed["schemaVersion"].as_i64()!=Some(1)||expected<0||parsed["revision"].as_i64()!=Some(expected+1){return Err("Invalid data version.".into());}for key in ["products","sales","refunds","sessions","expenses","purchases","movements","audit","held","suppliers"]{if !parsed[key].is_array(){return Err(format!("Invalid data collection: {}",key));}}
// A compare-and-swap inside one SQLite transaction prevents lost updates and partial saves.
let mut tx=db.pool.begin().await.map_err(|e|report(&db,e))?;let result=sqlx::query("UPDATE business_state SET data=?,revision=? WHERE id=1 AND revision=?").bind(&data).bind(expected+1).bind(expected).execute(&mut *tx).await.map_err(|e|report(&db,e))?;if result.rows_affected()!=1{return Err("Data changed in another window. Lock and reopen the workspace before retrying.".into());}tx.commit().await.map_err(|e|report(&db,e))?;Ok(())}
async fn backup(pool:&SqlitePool,path:&Path)->Result<(),String>{let data:String=sqlx::query_scalar("SELECT data FROM business_state WHERE id=1").fetch_one(pool).await.map_err(|e|e.to_string())?;if data.is_empty(){return Ok(());}let dir=path.join("backups");std::fs::create_dir_all(&dir).map_err(|e|e.to_string())?;let temporary=dir.join("snapshot.tmp");std::fs::write(&temporary,data).map_err(|e|e.to_string())?;std::fs::rename(&temporary,dir.join(format!("counter-{}.json",seconds()))).map_err(|e|e.to_string())?;let mut files:Vec<PathBuf>=std::fs::read_dir(&dir).map_err(|e|e.to_string())?.filter_map(|e|e.ok().map(|x|x.path())).filter(|p|p.extension().is_some_and(|s|s=="json")).collect();files.sort();if files.len()>30{for file in files.iter().take(files.len()-30){std::fs::remove_file(file).map_err(|e|e.to_string())?;}}Ok(())}
#[cfg_attr(mobile, tauri::mobile_entry_point)]
pub fn run(){tauri::Builder::default().plugin(tauri_plugin_dialog::init()).plugin(tauri_plugin_fs::init()).setup(|app|{let path=app.path().app_data_dir()?;std::fs::create_dir_all(&path)?;let options=SqliteConnectOptions::new().filename(path.join("counter.db")).create_if_missing(true).journal_mode(SqliteJournalMode::Wal).synchronous(SqliteSynchronous::Full).busy_timeout(Duration::from_secs(5));let pool=tauri::async_runtime::block_on(async {let pool=SqlitePoolOptions::new().max_connections(1).connect_with(options).await?;sqlx::query("CREATE TABLE IF NOT EXISTS owner (id INTEGER PRIMARY KEY CHECK(id=1),hash TEXT NOT NULL)").execute(&pool).await?;sqlx::query("CREATE TABLE IF NOT EXISTS business_state (id INTEGER PRIMARY KEY CHECK(id=1), revision INTEGER NOT NULL, data TEXT NOT NULL)").execute(&pool).await?;sqlx::query("INSERT OR IGNORE INTO business_state VALUES (1,0,'')").execute(&pool).await?;Ok::<_,sqlx::Error>(pool)})?;let timer_pool=pool.clone();let timer_path=path.clone();tauri::async_runtime::spawn(async move{loop{if let Err(e)=backup(&timer_pool,&timer_path).await{use std::io::Write;if let Ok(mut f)=std::fs::OpenOptions::new().create(true).append(true).open(timer_path.join("support.log")){let _=writeln!(f,"{} Automatic backup failed: {}",seconds(),e);}}tokio::time::sleep(Duration::from_secs(3600)).await;}});app.manage(Db{pool,auth:Mutex::new(Auth{unlocked:false,failures:0,blocked_until:0}),path});Ok(())}).invoke_handler(tauri::generate_handler![has_owner,create_owner,unlock,lock,change_password,load_state,save_state]).run(tauri::generate_context!()).expect("Unable to start Counter POS");}
